config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  :controllers => { :registrations => 'registrations' }
  root 'boards#index'
  resources :boards do
    resources :pins
  end
end

app/models/board.rb
class Board < ActiveRecord::Base

  has_many :pins,dependent: :destroy
  belongs_to :user

  validates_presence_of :title
  validates_presence_of :user
  self.per_page = 10

  def image(size=nil)
    unless pins.empty?
      pins.sample.image.url(size)
    end
  end
end

app/models/pin.rb
class Pin < ActiveRecord::Base

  belongs_to :board

  self.per_page = 15

  validates_presence_of :title
  has_attached_file :image,
                    :styles => {
                        medium: '400x400',
                        thumb: '100x100'}, :default_url => '/images/:style/missing.png'
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :boards
  validates_presence_of :name
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:edit,:destroy,:update]
  respond_to :html

  def index
    @boards = Board.paginate(page: params[:page])
    respond_with(@boards)
  end

  def show
    respond_with(@board)
  end

  def new
    @board = Board.new
    respond_with(@board)
  end

  def edit
  end

  def create
    @board = Board.new(board_params)
    @board.user = current_user
    @board.save
    respond_with(@board)
  end

  def update
    @board.update(board_params)
    respond_with(@board)
  end

  def destroy
    @board.destroy
    respond_with(@board)
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:title, :description)
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :set_board

  respond_to :html

  def index
    @pins = @board.pins.paginate(page: params[:page])
    respond_with(@board,@pins)
  end

  def show
    respond_with(@board,@pin)
  end

  def new
    @pin = Pin.new
    respond_with(@board,@pin)
  end

  def edit
  end

  def create
    @pin = Pin.new(pin_params)
    @pin.board = @board
    @pin.save
    respond_with(@board,@pin)
  end

  def update
    @pin.update(pin_params)
    respond_with(@board,@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@board,@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def set_board
      @board = Board.find(params[:board_id])
    end

    def pin_params
      params.require(:pin).permit(:title, :description,:image)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create]

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/boards/_board.html.haml
.board
  =link_to board_pins_path(board) do
    .title= board.title
    .image=image_tag board.image(:medium)
    .description= board.description

app/views/boards/_form.html.haml
= simple_form_for(@board) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description

  .form-actions
    = f.button :submit

app/views/boards/edit.html.haml
.page-header
  = link_to boards_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @board, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing board

= render 'form'

app/views/boards/index.html.haml
.page-header
  = link_to new_board_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Board

#boards-container
  .boards
    -@boards.each do |board|
      =render board
.pagination
  =will_paginate @boards

app/views/boards/new.html.haml
.page-header
  = link_to boards_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New board

= render 'form'

app/views/boards/show.html.haml
.page-header
  = link_to boards_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_board_path(@board), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show board

=render @board

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title Starter Template for Bootstrap

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#{root_path}"} Home
    .container
      .row
        .col-md-9
        - flash.each do |name, msg|
          = content_tag :div, :class => "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do
            %button.close{:type => "button", :data => {:dismiss => "alert"} }
              span{:aria => {:hidden => "true"} } &times;
              span.sr-only Close
            = msg
        = yield

app/views/pins/_form.html.haml
= simple_form_for([@board,@pin],html: {class: 'form-horizontal'}) do |f|
  - if @pin.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pin.errors.count, "error")} prohibited this pin from being saved:"
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg
  =f.association :board
  =f.input :title
  =f.input :description
  =f.input :image, as: :file
  =f.submit

app/views/pins/_pin.html.haml
.pin
  =link_to board_pin_path(pin.board,pin) do
    .title=pin.title
    .thumb.image=image_tag pin.image.url(:medium)
    .description=pin.description

app/views/pins/edit.html.haml
%h1 Editing pin

= render 'form'

= link_to 'Show', @pin
\|
= link_to 'Back', board_pins_path(@board.id)

app/views/pins/index.html.haml
.page-header
  %h1 Listing pins
  = link_to new_board_pin_path(@board), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Pin
#pins-container
  -@pins.each do |pin|
    =render pin
.pagination
  =will_paginate @pins

app/views/pins/new.html.haml
%h1 New pin

= render 'form'

= link_to 'Back', board_pins_path(@board)

app/views/pins/show.html.haml
%p#notice= notice

=render @pin

= link_to 'Edit', edit_board_pin_path(@board,@pin)
\|
= link_to 'Back', board_pins_path(@board)